// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        return linux;

      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
   apiKey: "AIzaSyDotSo5nz_0Z7IxIVVmEwR7w5ZTCtgKTBg",

  authDomain: "includeapp-2cee9.firebaseapp.com",

  projectId: "includeapp-2cee9",

  storageBucket: "includeapp-2cee9.firebasestorage.app",

  messagingSenderId: "654176978946",

  appId: "1:654176978946:web:6ccdf04a0e0fc02636ff1b"

  );

  static const FirebaseOptions android = FirebaseOptions(
   apiKey: "AIzaSyDotSo5nz_0Z7IxIVVmEwR7w5ZTCtgKTBg",

  authDomain: "includeapp-2cee9.firebaseapp.com",

  projectId: "includeapp-2cee9",

  storageBucket: "includeapp-2cee9.firebasestorage.app",

  messagingSenderId: "654176978946",

  appId: "1:654176978946:web:6ccdf04a0e0fc02636ff1b"

  );

  static const FirebaseOptions linux = FirebaseOptions(
   apiKey: "AIzaSyDotSo5nz_0Z7IxIVVmEwR7w5ZTCtgKTBg",

  authDomain: "includeapp-2cee9.firebaseapp.com",

  projectId: "includeapp-2cee9",

  storageBucket: "includeapp-2cee9.firebasestorage.app",

  messagingSenderId: "654176978946",

  appId: "1:654176978946:web:6ccdf04a0e0fc02636ff1b"

  );

  static const FirebaseOptions windows = FirebaseOptions(
   apiKey: "AIzaSyDotSo5nz_0Z7IxIVVmEwR7w5ZTCtgKTBg",

  authDomain: "includeapp-2cee9.firebaseapp.com",

  projectId: "includeapp-2cee9",

  storageBucket: "includeapp-2cee9.firebasestorage.app",

  messagingSenderId: "654176978946",

  appId: "1:654176978946:web:6ccdf04a0e0fc02636ff1b"

  );
}
